### ISSUE TITLE
[全版本]在旁观模式传送列表中无法加载皮肤

### ISSUE THREAD

**Issue by HeartyYF** [xfl03/MCCustomSkinLoader#14]
如题，只有正版皮肤可以被加载，其余的一概是Alex。。

**Comment by xfl03** [comment]
Fixed in 7dc2c45
(20170618)

**Comment by xfl03** [comment]
It maybe fixed again https://github.com/xfl03/MCCustomSkinLoader/commit/eee978fc83a6240ef9c4619e75a62a0eb92efada
More Test needed.

**Comment by xfl03** [comment]
Fixed in https://github.com/xfl03/MCCustomSkinLoader/commit/4449ccdd4530c0d6505df161abc77709a91c8a91
