### ISSUE TITLE
[特性]服务端皮肤管理

### ISSUE THREAD

**Issue by Mickeyxiami** [xfl03/MCCustomSkinLoader#22]
我觉得可以实现一套从服务端加载皮肤的方式，这部分可以依赖forge，玩家可以通过指令或者按键来激活更改皮肤的GUI，而不必通过皮肤站，如果服务端有该mod将默认开启此功能，便优先从服务端加载皮肤材质

**Comment by xfl03** [comment]
能否请您讲解下您所希望的具体实现？
以及..如果服务器有mod A，而客户端没有mod A，应该是进不去服务器的吧..
所以应该会以sponge plugin的形式出现。

目前您可以通过直接修改用户登陆时将要回传到客户端的GameProfile以实现服务器指定皮肤（不支持原版）。

**Comment by Mickeyxiami** [comment]
既然是forge端一般都是有对应的整合包，这一点基本可以忽略。
主要是希望可以在游戏中即时修改皮肤并立刻对别的玩家可见，可以不依赖皮肤站，像Skinme目前就不支持双层皮肤。
这个提议主要是从玩家的角度考虑
  1> 不需要去皮肤站注册和管理，不需要考虑皮肤站是否支持某些内容
  2> 避免了与别的来源的ID重复
  3> 修改即时可见
  4> 添加客户端gui便于操作

**Comment by g-plane** [comment]
个人观点，非喜请见谅：频繁修改皮肤的玩家不多吧？就算在游戏中修改了皮肤，貌似要重新进地图才能重新渲染皮肤的。

**Comment by xfl03** [comment]
@g-plane 根据一些与NPC相关的实际例子，应该是可以强制刷新的。

**Comment by xfl03** [comment]
@Mickeyxiami 我参考了下相关文档，准备使用plugin channels进行通信。以及，应该会在客户端使用原版代码，服务端推出sponge/bukkit版。

**Comment by Mickeyxiami** [comment]
下午折腾了一下，除了GUI的部分基本都实现了

**Comment by Mickeyxiami** [comment]
要不我close掉吧，我已经以独立forge mod的形式实现了，而且皮肤的刷新是瞬间（包括刚进入游戏的皮肤加载）

**Comment by xfl03** [comment]
希望这个功能可以直接加入CSL的主程序，这样或许会方便不少。
如果您已经开发完成，希望可以以GPLv3的形式直接使用您的代码；
如果不可以的话，我将自行开发使用forge来完成此功能。

**Comment by xfl03** [comment]
服务端算是完成了  
https://github.com/xfl03/CustomSkinServer/commit/a679d3abd598c59377f244f5965829b7111efa3e
接下来会开始客户端的开发
嗯..的确慢了一点..

**Comment by shanklm** [comment]
通过服务端插件控制皮肤站的选择是一个很方便的功能。。

1：通过服务器插件设置皮肤站的链接。
2：玩家进入服务器优选服务端插件配置的皮肤站链接！

我想只需要这2个功能实现就很厉害了·

**Comment by xfl03** [comment]
@shanklm 
我的想法是直接在游戏里通过GUI修改皮肤，服务器插件进行皮肤同步
而不是一个传统意义上的皮肤按列表联网加载
