### ISSUE TITLE
默认加载列表是不是写错了？

### ISSUE THREAD

**Issue by g-plane** [xfl03/MCCustomSkinLoader#25]
https://github.com/xfl03/MCCustomSkinLoader/blob/d6281881a52e49d5e7222bde07309de5f4ce73ee/Common/source/customskinloader/CustomSkinLoader.java#L36
写了两个 `http://`？

**Comment by xfl03** [comment]
其实这个内容直接评论就好了~
本地已修改~下次一起提交~

**Comment by xfl03** [comment]
https://github.com/xfl03/MCCustomSkinLoader/commit/7dc2c4560060758a2c1f3cc08f84bbbfa8d76cce 
已提交~
