### ISSUE TITLE
Exception occurs while loading via UniSkinApi 

### ISSUE THREAD

**Issue by zhyupe** [xfl03/MCCustomSkinLoader#27]
According to the UniSkinApi specification:
> All the fields are optional, and a compatible client should automatically skip any missing information.

However, if the server doesn't provide model_preference, following exception occurs.
> [2017-07-02 16:02:13] [- WARNING] Exception occurs while loading.
> [2017-07-02 16:02:13] [- WARNING] Exception: java.lang.NullPointerException
> [2017-07-02 16:02:13] [- WARNING] customskinloader.loader.jsonapi.UniSkinAPI.toUserProfile(UniSkinAPI.java:40)
> [2017-07-02 16:02:13] [- WARNING] customskinloader.loader.JsonAPILoader.loadProfile(JsonAPILoader.java:77)
> [2017-07-02 16:02:13] [- WARNING] customskinloader.CustomSkinLoader.loadProfile0(CustomSkinLoader.java:97)
> [2017-07-02 16:02:13] [- WARNING] customskinloader.CustomSkinLoader.loadProfile(CustomSkinLoader.java:73)
> [2017-07-02 16:02:13] [- WARNING] customskinloader.fake.FakeSkinManager$1.run(FakeSkinManager.java:61)
> [2017-07-02 16:02:13] [- WARNING] java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> [2017-07-02 16:02:13] [- WARNING] java.util.concurrent.FutureTask.run(Unknown Source)
> [2017-07-02 16:02:13] [- WARNING] java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> [2017-07-02 16:02:13] [- WARNING] java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> [2017-07-02 16:02:13] [- WARNING] java.lang.Thread.run(Unknown Source)

**Comment by xfl03** [comment]
Please check if the server is using UniSkinAPI.
Or give me the link of root.
